#!/bin/bash
# Quick Commands Reference for BroBillionaire Internal Linking

echo "=========================================="
echo "BroBillionaire Internal Linking Tools"
echo "=========================================="
echo ""
echo "1. Run Internal Linking (Add links to articles & tools):"
echo "   python3 internal-linking-seo.py"
echo ""
echo "2. Enhance Tool Pages (Add content, FAQs, schema):"
echo "   python3 enhance-tool-pages.py"
echo ""
echo "3. Verify Implementation (Check progress):"
echo "   python3 verify-internal-linking.py"
echo ""
echo "4. Add Remaining Mappings:"
echo "   python3 add-remaining-mappings.py"
echo ""
echo "=========================================="
echo "Current Status:"
echo "=========================================="
python3 verify-internal-linking.py 2>/dev/null | grep -A 15 "COMPLETION STATUS" | head -5
echo ""
echo "=========================================="
echo "Quick Actions:"
echo "=========================================="
echo ""
echo "Run all scripts in sequence:"
echo "   python3 internal-linking-seo.py && python3 enhance-tool-pages.py && python3 verify-internal-linking.py"
echo ""
echo "Check specific file for links:"
echo "   grep -o 'href=\"tool-[^\"]*\"' article-YOUR-FILE.html | wc -l"
echo ""
echo "Find articles without tool links:"
echo "   for f in article-*.html; do grep -q 'Related Tools' \$f || echo \$f; done | head -10"
echo ""
echo "Find tools without article links:"
echo "   for f in tool-*.html; do grep -q 'Related Articles' \$f || echo \$f; done | head -10"
echo ""
